if(DEFINED DAQMODULES_OPCUA_CMAKE_OPTIONS_INCLUDED)
  return()
endif()
set(DAQMODULES_OPCUA_CMAKE_OPTIONS_INCLUDED TRUE)

cmake_dependent_option(OPCUA_ENABLE_ENCRYPTION "Enable OpcUa encryption" OFF "OPENDAQ_ENABLE_OPCUA OR NOT DAQMODULES_OPCUA_BUILDING_AS_SUBMODULE" OFF)
