include_guard(GLOBAL)

message(STATUS "Include OpcUa module custom cmake options")

cmake_dependent_option(OPCUA_ENABLE_ENCRYPTION "Enable OpcUa encryption" OFF "OPENDAQ_ENABLE_OPCUA OR NOT DAQMODULES_OPCUA_BUILDING_AS_SUBMODULE" OFF)
cmake_dependent_option(OPENDAQ_ENABLE_OPCUA_INTEGRATION_TESTS "Enable OpcUa integration testing" ON "DAQMODULES_OPCUA_BUILDING_AS_SUBMODULE AND OPENDAQ_ENABLE_OPCUA AND OPENDAQ_ENABLE_TESTS OR DAQMODULES_OPCUA_ENABLE_TESTS" OFF)
